[project]
name = "gpt-paper-title"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">3.9"
dependencies = [
    "httpx==0.25.1",
    "numpy==1.26.0",
    "openai==1.3.1",
    "pandas==2.1.1",
    "pypdf2==2.10.5",
    "scikit-learn==1.3.0",
]
